name: Deploy Webapp

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_ami:

    # runner
    runs-on: ubuntu-latest

    steps:

      # Install Packages
      - name: Install apt & zip
        run: sudo apt-get update && sudo apt-get install wget zip unzip -y

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Zip Artifact
      - name: Zip Artifact
        run: |
          mkdir -p codedeploy_artifact
          zip -r webapp-${{github.event.pull_request.id}}.zip \
          ./webappone/target/webappone-0.0.1-SNAPSHOT.jar codedeploy/*.sh appspec.yml
          mv webapp-${{github.event.pull_request.id}}.zip codedeploy_artifact/

      # Upload Artifacts to S3
      - name: Upload Artifacts
        run: |
          aws s3 cp ./codedeploy_artifact/webapp-${{github.event.pull_request.id}}.zip s3://${{ secrets.S3_BUCKET_NAME }}


      # Deploy Artifact to EC2
      - name: Deploy Webapp
        run: |
          aws deploy create-deployment \
          --application-name "csye6225-webapp" \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name "csye6225-webapp-deployment" \
          --description "deployed webapp" \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=webapp-${{github.event.pull_request.id}}.zip
