name: Unit Test on PR

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_ami:

    # runner
    runs-on: ubuntu-latest

    steps:

      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run Tests
      - name: Run all Tests
        run: |
          cd webappone
          mvn test
          cd ..